site_name: 大梦千秋的笔记
#site_url: https://www.fernandocelmer.com/
#copyright: Fernando Celmer

nav:
  - Home: index.md
  - ops:
      - 从零开始部署CICD集群: 从零开始部署CICD集群.md
      - 更多: more.md
#  - dev:
#      - nav/development/development-guide.md
#      - nav/development/release-notes.md

theme:
    name: simple-blog
    favicon: assets/favicon.ico
    logo: assets/logo.png
    theme_style: light
    site_name_style: bold
    title_style: bold
    colors:
      text: black
      title: black
      primary: black
      background: white
    components:
      site_name: true
      title: true
      menu: true
      preview: true
      footer: true
extra:
  generator: false

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
