site_name: 大梦千秋的笔记
#site_url: https://www.fernandocelmer.com/
#copyright: Fernando Celmer

nav:
  - Home: index.md
  - Getting Started: nav/getting-started.md
  - Setup:
      - nav/setup/components.md
      - nav/setup/colors.md
      - nav/setup/fonts.md
      - nav/setup/logo.md
      - nav/setup/favicon.md
  - Development:
      - nav/development/development-guide.md
      - nav/development/release-notes.md

theme:
    name: simple-blog
    favicon: assets/favicon.ico
    logo: assets/logo.png
    theme_style: light
    site_name_style: normal
    title_style: bold
    colors:
      text: black
      title: black
      primary: black
      background: white
    components:
      site_name: true
      title: true
      menu: true
      preview: true
      footer: true
#    palette:
#
#    # Light mode
#    - media: "(prefers-color-scheme: light)"
#      scheme: default
#      primary: pink
#      accent: indigo
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to dark mode
#
#    # Dark mode
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate
#      primary: pink
#      accent: blue
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
